
server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    com.datastax.demo: INFO
    com.datastax.astra: INFO
    com.datastax.stargate: INFO
    com.datastax.oss: ERROR
    org.junit.vintage: ERROR

spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: XHTML
    prefix: classpath:views/view-
    suffix: .html
  jackson:
    default-property-inclusion: non-null
     
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: false
  group-configs:
    - group: Rest Controllers (Spring MVC)
      packages-to-scan: com.datastax.demo.stargate
      
# Properties exopected by the starter
astra:

  # Credentials to DB
  client-id: <CLIENT_ID>
  client-secret: <CLIENT_SECRET>
  application-token: <APP_TOKEN>

  # Select an instance
  cloud-region: <DB_REGION>
  database-id: <DB_ID>
  keyspace: stargate 




